name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      testType:
        description: 'Выбор сборки (api, ui, all)'
        required: true
        default: 'all'

permissions:
  contents: write

jobs:
  api-tests:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.testType == 'api' || github.event.inputs.testType == 'all' }}
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run API tests with @api tag
        run: ./gradlew clean test --info -DincludeTags=api || true
        env:
          ALLURE_RESULTS_PATH: build/allure-results

      - name: Upload API Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-api-results
          path: build/allure-results

  ui-tests:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.testType == 'ui' || github.event.inputs.testType == 'all' }}
    name: UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run UI tests with @ui tag
        run: ./gradlew clean test --info -DincludeTags=ui || true
        env:
          ALLURE_RESULTS_PATH: build/allure-results

      - name: Upload UI Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui-results
          path: build/allure-results
