name: Run API/UI Tests and Publish Allure Report

on: [push, pull_request]

jobs:
  api-tests:
    name: Run API Tests by @Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run API tests with @api tag
        run: ./gradlew clean test --info -DincludeTags=api
        env:
          ALLURE_RESULTS_PATH: build/allure-results

      - name: Upload API Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-api-results
          path: build/allure-results

  ui-tests:
    name: Run UI Tests by @Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run UI tests with @ui tag
        run: ./gradlew clean test --info -DincludeTags=ui
        env:
          ALLURE_RESULTS_PATH: build/allure-results

      - name: Upload UI Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-ui-results
          path: build/allure-results

  allure-report:
    name: Generate and Publish Allure Report
    runs-on: ubuntu-latest
    needs: [api-tests, ui-tests]

    steps:
      - name: Download API results
        uses: actions/download-artifact@v4
        with:
          name: allure-api-results
          path: allure-results/api

      - name: Download UI results
        uses: actions/download-artifact@v4
        with:
          name: allure-ui-results
          path: allure-results/ui

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          ALLURE_VERSION="2.34.0"
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
          unzip allure-${ALLURE_VERSION}.zip -d /opt/
          sudo ln -sf /opt/allure-${ALLURE_VERSION}/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure report
        run: |
          mkdir -p merged-results
          cp -r allure-results/api/* merged-results/ || true
          cp -r allure-results/ui/* merged-results/ || true
          allure generate merged-results -o allure-report

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/main@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: main
          force_orphan: true
